In [1]:
import pandas as pd

In [2]:
import os

In [3]:
df = pd.read_csv("../Data/bakery.csv")
df

,data-product-id,data-product-name,data-product-type,data-product-on-offer,data-product-index,image-url,product-page,product-name,product-size,item-price,price-per-unit,offer-description,category
0,872615,Mr Kipling Viennese Whirls,G,True,246,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/mr-kipl...,Mr Kipling Viennese Whirls,6s,£1.98,33p each,25% Off. Was £2.65,Bakery
1,56312,Mr Kipling French Fancies,G,True,161,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/mr-kipl...,Mr Kipling French Fancies,8s,£2.36,29.5p each,25% Off. Was £3.15,Bakery
2,684311,Mr Kipling 8 Angel Slices,G,True,277,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/mr-kipl...,Mr Kipling 8 Angel Slices,8s,£2.96,37p each,25% Off. Was £3.95,Bakery
3,540706,Waitrose 4 Brioche Burger Buns,G,True,4,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/waitros...,Waitrose 4 Brioche Burger Buns,4s,£1.31,32.8p each,25% Off. Was £1.75,Bakery
4,783454,Hovis Seed Sensations Multiseeded Sliced Bread,G,False,5,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/hovis-s...,Hovis Seed Sensations Multiseeded Sliced Bread,800g,£1.90,23.8p/100g,NaN,Bakery
...,...,...,...,...,...,...,...,...,...,...,...,...,...
480,384230,Galaxy Chocolate Cake Bars,G,False,481,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/galaxy-...,Galaxy Chocolate Cake Bars,5s,£2.25,45p each,NaN,Bakery
481,376437,25cm Football Cake,E,False,482,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/25cm-fo...,25cm Football Cake,each,£30.00,£30 each,NaN,Bakery
482,374515,Waitrose Ready To Bake 4 All Butter Cinnamon S...,G,True,483,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/waitros...,Waitrose Ready To Bake 4 All Butter Cinnamon S...,360g,£2.60,£7.23/kg,Introductory Offer.Will be £3.30,Bakery
483,297903,Dr. Oetker Old School Cake Mix Vanilla,G,False,484,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/dr-oetk...,Dr. Oetker Old School Cake Mix Vanilla,436g,£3.00,£6.89/kg,NaN,Bakery
484,77133,Cohens Bakery Buckingham Rye Bread,G,False,485,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/cohens-...,Cohens Bakery Buckingham Rye Bread,400g,£2.10,52.5p/100g,NaN,Bakery

In [ ]:
 # How many rows and columns
 df.shape

(485, 13)

In [6]:
#list all the columns 
df.columns

Index(['data-product-id', 'data-product-name', 'data-product-type',
       'data-product-on-offer', 'data-product-index', 'image-url',
       'product-page', 'product-name', 'product-size', 'item-price',
       'price-per-unit', 'offer-description', 'category'],
      dtype='object')

In [7]:
#view subset of columns
df[['product-name', 'item-price', 'category']]

                                          product-name item-price category
0                           Mr Kipling Viennese Whirls      £1.98   Bakery
1                            Mr Kipling French Fancies      £2.36   Bakery
2                            Mr Kipling 8 Angel Slices      £2.96   Bakery
3                       Waitrose 4 Brioche Burger Buns      £1.31   Bakery
4       Hovis Seed Sensations Multiseeded Sliced Bread      £1.90   Bakery
..                                                 ...        ...      ...
480                         Galaxy Chocolate Cake Bars      £2.25   Bakery
481                                 25cm Football Cake     £30.00   Bakery
482  Waitrose Ready To Bake 4 All Butter Cinnamon S...      £2.60   Bakery
483             Dr. Oetker Old School Cake Mix Vanilla      £3.00   Bakery
484                 Cohens Bakery Buckingham Rye Bread      £2.10   Bakery

[485 rows x 3 columns]

In [ ]:
#top 5 rows
df.head(5)

,data-product-id,data-product-name,data-product-type,data-product-on-offer,data-product-index,image-url,product-page,product-name,product-size,item-price,price-per-unit,offer-description,category
0,872615,Mr Kipling Viennese Whirls,G,True,246,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/mr-kipl...,Mr Kipling Viennese Whirls,6s,£1.98,33p each,25% Off. Was £2.65,Bakery
1,56312,Mr Kipling French Fancies,G,True,161,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/mr-kipl...,Mr Kipling French Fancies,8s,£2.36,29.5p each,25% Off. Was £3.15,Bakery
2,684311,Mr Kipling 8 Angel Slices,G,True,277,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/mr-kipl...,Mr Kipling 8 Angel Slices,8s,£2.96,37p each,25% Off. Was £3.95,Bakery
3,540706,Waitrose 4 Brioche Burger Buns,G,True,4,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/waitros...,Waitrose 4 Brioche Burger Buns,4s,£1.31,32.8p each,25% Off. Was £1.75,Bakery
4,783454,Hovis Seed Sensations Multiseeded Sliced Bread,G,False,5,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/hovis-s...,Hovis Seed Sensations Multiseeded Sliced Bread,800g,£1.90,23.8p/100g,NaN,Bakery

In [9]:
df.iloc[0]

data-product-id                                                     872615
data-product-name                               Mr Kipling Viennese Whirls
data-product-type                                                        G
data-product-on-offer                                                 True
data-product-index                                                     246
image-url                https://ecom-su-static-prod.wtrecom.com/images...
product-page             https://www.waitrose.com/ecom/products/mr-kipl...
product-name                                    Mr Kipling Viennese Whirls
product-size                                                            6s
item-price                                                           £1.98
price-per-unit                                                    33p each
offer-description                                       25% Off. Was £2.65
category                                                            Bakery
Name: 0, dtype: object

In [10]:
df.iloc[0,2]

'G'

In [11]:
df.query('`product-size` == "800g"')

,data-product-id,data-product-name,data-product-type,data-product-on-offer,data-product-index,image-url,product-page,product-name,product-size,item-price,price-per-unit,offer-description,category
4,783454,Hovis Seed Sensations Multiseeded Sliced Bread,G,False,5,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/hovis-s...,Hovis Seed Sensations Multiseeded Sliced Bread,800g,£1.90,23.8p/100g,NaN,Bakery
6,75319,Waitrose Super Soft White Medium Sliced,G,False,7,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/waitros...,Waitrose Super Soft White Medium Sliced,800g,£1.00,12.5p/100g,NaN,Bakery
10,837159,Jacksons Multigrain Brown Bloomer,G,False,11,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/jackson...,Jacksons Multigrain Brown Bloomer,800g,£1.85,23.1p/100g,NaN,Bakery
11,818881,Waitrose Soft White Toastie Thick Sliced,G,False,12,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/waitros...,Waitrose Soft White Toastie Thick Sliced,800g,£1.00,12.5p/100g,NaN,Bakery
12,563526,Jacksons Soft White Bloomer,G,False,13,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/jackson...,Jacksons Soft White Bloomer,800g,£1.85,23.1p/100g,NaN,Bakery
17,55041,Waitrose Wholemeal Farmhouse Medium Sliced,G,False,18,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/waitros...,Waitrose Wholemeal Farmhouse Medium Sliced,800g,£1.45,18.1p/100g,NaN,Bakery
20,520256,Black Sheep Craft Bakery White Tiger Bloomer,G,False,21,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/black-s...,Black Sheep Craft Bakery White Tiger Bloomer,800g,£2.00,25p/100g,NaN,Bakery
22,463468,Waitrose Multi-Seeded Farmhouse,G,False,23,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/waitros...,Waitrose Multi-Seeded Farmhouse,800g,£1.55,19.4p/100g,NaN,Bakery
29,84740,Hovis Best of Both Medium Sliced Bread,G,False,30,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/hovis-b...,Hovis Best of Both Medium Sliced Bread,800g,£1.35,16.9p/100g,NaN,Bakery
31,55047,Hovis Wholemeal Medium Sliced Bread,G,False,32,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/hovis-w...,Hovis Wholemeal Medium Sliced Bread,800g,£1.45,18.1p/100g,NaN,Bakery
34,3062,Hovis Soft White Medium Sliced White Bread,G,False,35,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/hovis-s...,Hovis Soft White Medium Sliced White Bread,800g,£1.45,18.1p/100g,NaN,Bakery
52,827079,Jacksons Multiseed Bloomer,G,False,53,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/jackson...,Jacksons Multiseed Bloomer,800g,£1.85,23.1p/100g,NaN,Bakery
56,55416,Hovis Original Granary Medium Sliced Bread,G,False,57,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/hovis-o...,Hovis Original Granary Medium Sliced Bread,800g,£1.90,23.8p/100g,NaN,Bakery
62,515769,Waitrose Soft White Farmhouse,G,False,63,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/waitros...,Waitrose Soft White Farmhouse,800g,£1.45,18.1p/100g,NaN,Bakery
64,90605,Hovis Soft White Thick Sliced White Bread,G,False,65,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/hovis-s...,Hovis Soft White Thick Sliced White Bread,800g,£1.45,18.1p/100g,NaN,Bakery
67,41103,Waitrose Multigrain Farmhouse,G,False,68,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/waitros...,Waitrose Multigrain Farmhouse,800g,£1.55,19.4p/100g,NaN,Bakery
70,432291,Wholemeal Heyford,G,False,71,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/wholeme...,Wholemeal Heyford,800g,£2.00,25p/100g,NaN,Bakery
79,55051,Essential Wholemeal Medium Sliced Bread,G,False,80,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/essenti...,Essential Wholemeal Medium Sliced Bread,800g,75p,9.4p/100g,NaN,Bakery
83,91814,Hovis Wholemeal Thick Sliced Bread,G,False,84,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/hovis-w...,Hovis Wholemeal Thick Sliced Bread,800g,£1.45,18.1p/100g,NaN,Bakery
85,35513,Vogel's Soya & Linseed Bread,G,False,86,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/vogels-...,Vogel's Soya & Linseed Bread,800g,£2.40,30p/100g,NaN,Bakery
104,54266,Hovis Granary Wholemeal Sliced Bread,G,False,105,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/hovis-g...,Hovis Granary Wholemeal Sliced Bread,800g,£1.90,23.8p/100g,NaN,Bakery
109,55428,Vogel's Original Mixed Grain Bread,G,False,110,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/vogels-...,Vogel's Original Mixed Grain Bread,800g,£2.40,30p/100g,NaN,Bakery
119,654238,Jacksons Super Seeded Bloomer,G,False,120,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/jackson...,Jacksons Super Seeded Bloomer,800g,£2.00,25p/100g,NaN,Bakery
139,572562,Jackson's Tiger Bloomer,G,True,140,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/jackson...,Jackson's Tiger Bloomer,800g,£1.56,19.5p/100g,20% Off. Was £1.95,Bakery
178,55018,Essential White Medium Sliced Bread,G,False,179,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/essenti...,Essential White Medium Sliced Bread,800g,75p,9.4p/100g,NaN,Bakery
229,559508,Jacksons Bloomin' Both,G,False,230,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/jackson...,Jacksons Bloomin' Both,800g,£1.75,21.9p/100g,NaN,Bakery
242,527601,Granary® Loaf,G,False,243,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/granary...,Granary® Loaf,800g,£2.00,25p/100g,NaN,Bakery
320,465070,Hovis Seed Sensations Malted Wholegrain Loaf,G,False,321,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/hovis-s...,Hovis Seed Sensations Malted Wholegrain Loaf,800g,£1.90,£2.38/kg,NaN,Bakery

In [13]:
df.query('`product-size` == "800g"')[['product-name', 'item-price', 'category']]

                                       product-name item-price category
4    Hovis Seed Sensations Multiseeded Sliced Bread      £1.90   Bakery
6           Waitrose Super Soft White Medium Sliced      £1.00   Bakery
10                Jacksons Multigrain Brown Bloomer      £1.85   Bakery
11         Waitrose Soft White Toastie Thick Sliced      £1.00   Bakery
12                      Jacksons Soft White Bloomer      £1.85   Bakery
17       Waitrose Wholemeal Farmhouse Medium Sliced      £1.45   Bakery
20     Black Sheep Craft Bakery White Tiger Bloomer      £2.00   Bakery
22                  Waitrose Multi-Seeded Farmhouse      £1.55   Bakery
29           Hovis Best of Both Medium Sliced Bread      £1.35   Bakery
31              Hovis Wholemeal Medium Sliced Bread      £1.45   Bakery
34       Hovis Soft White Medium Sliced White Bread      £1.45   Bakery
52                       Jacksons Multiseed Bloomer      £1.85   Bakery
56       Hovis Original Granary Medium Sliced Bread      £1.90   Bakery
62                    Waitrose Soft White Farmhouse      £1.45   Bakery
64        Hovis Soft White Thick Sliced White Bread      £1.45   Bakery
67                    Waitrose Multigrain Farmhouse      £1.55   Bakery
70                                Wholemeal Heyford      £2.00   Bakery
79          Essential Wholemeal Medium Sliced Bread        75p   Bakery
83               Hovis Wholemeal Thick Sliced Bread      £1.45   Bakery
85                     Vogel's Soya & Linseed Bread      £2.40   Bakery
104            Hovis Granary Wholemeal Sliced Bread      £1.90   Bakery
109              Vogel's Original Mixed Grain Bread      £2.40   Bakery
119                   Jacksons Super Seeded Bloomer      £2.00   Bakery
139                         Jackson's Tiger Bloomer      £1.56   Bakery
178             Essential White Medium Sliced Bread        75p   Bakery
229                          Jacksons Bloomin' Both      £1.75   Bakery
242                                   Granary® Loaf      £2.00   Bakery
320    Hovis Seed Sensations Malted Wholegrain Loaf      £1.90   Bakery

In [14]:
df[df['product-name'].str.contains('Sliced')][['product-name', 'item-price', 'category']]

                                       product-name item-price category
4    Hovis Seed Sensations Multiseeded Sliced Bread      £1.90   Bakery
6           Waitrose Super Soft White Medium Sliced      £1.00   Bakery
8               Hovis Wholemeal Medium Sliced Bread      £1.10   Bakery
11         Waitrose Soft White Toastie Thick Sliced      £1.00   Bakery
17       Waitrose Wholemeal Farmhouse Medium Sliced      £1.45   Bakery
23   Hovis Seed Sensations Multiseeded Sliced Bread      £1.20   Bakery
29           Hovis Best of Both Medium Sliced Bread      £1.35   Bakery
31              Hovis Wholemeal Medium Sliced Bread      £1.45   Bakery
34       Hovis Soft White Medium Sliced White Bread      £1.45   Bakery
54        Hovis Original Granary Thick Sliced Bread      £1.25   Bakery
56       Hovis Original Granary Medium Sliced Bread      £1.90   Bakery
61                   Hovis 1886 Seeded Sliced Bread      £1.50   Bakery
64        Hovis Soft White Thick Sliced White Bread      £1.45   Bakery
78                     Waitrose Sliced Brioche Loaf      £2.75   Bakery
79          Essential Wholemeal Medium Sliced Bread        75p   Bakery
83               Hovis Wholemeal Thick Sliced Bread      £1.45   Bakery
84        Waitrose Wholemeal Farmhouse Thick Sliced      £1.10   Bakery
104            Hovis Granary Wholemeal Sliced Bread      £1.90   Bakery
107     Waitrose Free From Gluten Sliced Seeded Cob      £3.10   Bakery
114               No.1 Wheat & Rye Sourdough Sliced      £2.20   Bakery
116                         Soreen Sliced Malt Loaf      £1.60   Bakery
173                  Wildfarmed Sliced Seeded Bread      £2.80   Bakery
178             Essential White Medium Sliced Bread        75p   Bakery
203                   Wildfarmed Sliced White Bread      £2.80   Bakery
227                 Hovis 1886 Granary Sliced Bread      £1.50   Bakery
230           Livlife Seriously Seeded Sliced Bread      £2.00   Bakery
265                  Deli Kitchen 4 Sliced Foccacia      £1.75   Bakery

In [15]:
df[(df['product-name'].str.contains('Bread')) & (df['product-size'] == '800g')]

,data-product-id,data-product-name,data-product-type,data-product-on-offer,data-product-index,image-url,product-page,product-name,product-size,item-price,price-per-unit,offer-description,category
4,783454,Hovis Seed Sensations Multiseeded Sliced Bread,G,False,5,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/hovis-s...,Hovis Seed Sensations Multiseeded Sliced Bread,800g,£1.90,23.8p/100g,NaN,Bakery
29,84740,Hovis Best of Both Medium Sliced Bread,G,False,30,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/hovis-b...,Hovis Best of Both Medium Sliced Bread,800g,£1.35,16.9p/100g,NaN,Bakery
31,55047,Hovis Wholemeal Medium Sliced Bread,G,False,32,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/hovis-w...,Hovis Wholemeal Medium Sliced Bread,800g,£1.45,18.1p/100g,NaN,Bakery
34,3062,Hovis Soft White Medium Sliced White Bread,G,False,35,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/hovis-s...,Hovis Soft White Medium Sliced White Bread,800g,£1.45,18.1p/100g,NaN,Bakery
56,55416,Hovis Original Granary Medium Sliced Bread,G,False,57,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/hovis-o...,Hovis Original Granary Medium Sliced Bread,800g,£1.90,23.8p/100g,NaN,Bakery
64,90605,Hovis Soft White Thick Sliced White Bread,G,False,65,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/hovis-s...,Hovis Soft White Thick Sliced White Bread,800g,£1.45,18.1p/100g,NaN,Bakery
79,55051,Essential Wholemeal Medium Sliced Bread,G,False,80,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/essenti...,Essential Wholemeal Medium Sliced Bread,800g,75p,9.4p/100g,NaN,Bakery
83,91814,Hovis Wholemeal Thick Sliced Bread,G,False,84,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/hovis-w...,Hovis Wholemeal Thick Sliced Bread,800g,£1.45,18.1p/100g,NaN,Bakery
85,35513,Vogel's Soya & Linseed Bread,G,False,86,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/vogels-...,Vogel's Soya & Linseed Bread,800g,£2.40,30p/100g,NaN,Bakery
104,54266,Hovis Granary Wholemeal Sliced Bread,G,False,105,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/hovis-g...,Hovis Granary Wholemeal Sliced Bread,800g,£1.90,23.8p/100g,NaN,Bakery
109,55428,Vogel's Original Mixed Grain Bread,G,False,110,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/vogels-...,Vogel's Original Mixed Grain Bread,800g,£2.40,30p/100g,NaN,Bakery
178,55018,Essential White Medium Sliced Bread,G,False,179,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/essenti...,Essential White Medium Sliced Bread,800g,75p,9.4p/100g,NaN,Bakery