In [23]:
import random
random_numbers = [random.randint(1, 100) for i in range(10)]

Create a list of random integers and calculate the sum of all the numbers in the list.

In [24]:
print(random_numbers)
print(sum(random_numbers))

[10, 55, 45, 86, 92, 67, 91, 6, 80, 14]
546

Write code that identifies the position of the smallest number in a list of numbers. Ensure your code works for any list of numbers.

In [25]:
x = [9, 11, 1, 7, 2]
x.index(min(x))

2

Write code that identifies the position of all even numbers in a list of numbers.

In [26]:
x = [2, 5, 6, 7, 8, 9]
for i in x:
    if i % 2 == 0:
        print(f"Even number {i} is at position {x.index(i)}")
    else:
        print(f"Odd number {i} is at position {x.index(i)}")

Even number 2 is at position 0
Odd number 5 is at position 1
Even number 6 is at position 2
Odd number 7 is at position 3
Even number 8 is at position 4
Odd number 9 is at position 5

Changing Column Names and Dropping Duplicate Rows

In [27]:
import pandas as pd

In [28]:
df = pd.read_csv("../Data/bakery.csv")

In [29]:
df

,data-product-id,data-product-name,data-product-type,data-product-on-offer,data-product-index,image-url,product-page,product-name,product-size,item-price,price-per-unit,offer-description,category
0,872615,Mr Kipling Viennese Whirls,G,True,246,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/mr-kipl...,Mr Kipling Viennese Whirls,6s,£1.98,33p each,25% Off. Was £2.65,Bakery
1,56312,Mr Kipling French Fancies,G,True,161,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/mr-kipl...,Mr Kipling French Fancies,8s,£2.36,29.5p each,25% Off. Was £3.15,Bakery
2,684311,Mr Kipling 8 Angel Slices,G,True,277,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/mr-kipl...,Mr Kipling 8 Angel Slices,8s,£2.96,37p each,25% Off. Was £3.95,Bakery
3,540706,Waitrose 4 Brioche Burger Buns,G,True,4,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/waitros...,Waitrose 4 Brioche Burger Buns,4s,£1.31,32.8p each,25% Off. Was £1.75,Bakery
4,783454,Hovis Seed Sensations Multiseeded Sliced Bread,G,False,5,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/hovis-s...,Hovis Seed Sensations Multiseeded Sliced Bread,800g,£1.90,23.8p/100g,NaN,Bakery
...,...,...,...,...,...,...,...,...,...,...,...,...,...
480,384230,Galaxy Chocolate Cake Bars,G,False,481,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/galaxy-...,Galaxy Chocolate Cake Bars,5s,£2.25,45p each,NaN,Bakery
481,376437,25cm Football Cake,E,False,482,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/25cm-fo...,25cm Football Cake,each,£30.00,£30 each,NaN,Bakery
482,374515,Waitrose Ready To Bake 4 All Butter Cinnamon S...,G,True,483,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/waitros...,Waitrose Ready To Bake 4 All Butter Cinnamon S...,360g,£2.60,£7.23/kg,Introductory Offer.Will be £3.30,Bakery
483,297903,Dr. Oetker Old School Cake Mix Vanilla,G,False,484,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/dr-oetk...,Dr. Oetker Old School Cake Mix Vanilla,436g,£3.00,£6.89/kg,NaN,Bakery
484,77133,Cohens Bakery Buckingham Rye Bread,G,False,485,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/cohens-...,Cohens Bakery Buckingham Rye Bread,400g,£2.10,52.5p/100g,NaN,Bakery

In [30]:
df.columns

Index(['data-product-id', 'data-product-name', 'data-product-type',
       'data-product-on-offer', 'data-product-index', 'image-url',
       'product-page', 'product-name', 'product-size', 'item-price',
       'price-per-unit', 'offer-description', 'category'],
      dtype='object')

Take a look at the columns data-product-name and product-name. Write code that establishes, without a doubt, whether these two columns are identical or not. If they are identical, drop one of the columns. If they are not, how would you modify the column names to make them consistent?

In [31]:
print(f"Are the columns identical? {df['product-name'].equals(df['data-product-name'])}")

if df['product-name'].equals(df['data-product-name']):
    print("The columns are identical. Dropping the 'data-product-name' column as it is redundant.")
    df = df.drop(columns=['data-product-name'])
else:
    print("The columns are not identical. Consider renaming the columns.")

Are the columns identical? True
The columns are identical. Dropping the 'data-product-name' column as it is redundant.

Change the column names to more concise and meaningful names. For example, data-product-id can be renamed to the much simpler id, product-name to name, and so on. Feel free to make your own choices, just be consistent.

In [32]:
df = df.rename(columns={"product-name":"name",
                                      "data-product-id":"id",
                                      "item-price":"price"})

In [33]:
df.info

<bound method DataFrame.info of          id data-product-type  data-product-on-offer  data-product-index  \
0    872615                 G                   True                 246
1     56312                 G                   True                 161
2    684311                 G                   True                 277
3    540706                 G                   True                   4
4    783454                 G                  False                   5
..      ...               ...                    ...                 ...
480  384230                 G                  False                 481
481  376437                 E                  False                 482
482  374515                 G                   True                 483
483  297903                 G                  False                 484
484   77133                 G                  False                 485

                                             image-url  \
0    https://ecom-su-static-prod.wtrecom.com/images...
1    https://ecom-su-static-prod.wtrecom.com/images...
2    https://ecom-su-static-prod.wtrecom.com/images...
3    https://ecom-su-static-prod.wtrecom.com/images...
4    https://ecom-su-static-prod.wtrecom.com/images...
..                                                 ...
480  https://ecom-su-static-prod.wtrecom.com/images...
481  https://ecom-su-static-prod.wtrecom.com/images...
482  https://ecom-su-static-prod.wtrecom.com/images...
483  https://ecom-su-static-prod.wtrecom.com/images...
484  https://ecom-su-static-prod.wtrecom.com/images...

                                          product-page  \
0    https://www.waitrose.com/ecom/products/mr-kipl...
1    https://www.waitrose.com/ecom/products/mr-kipl...
2    https://www.waitrose.com/ecom/products/mr-kipl...
3    https://www.waitrose.com/ecom/products/waitros...
4    https://www.waitrose.com/ecom/products/hovis-s...
..                                                 ...
480  https://www.waitrose.com/ecom/products/galaxy-...
481  https://www.waitrose.com/ecom/products/25cm-fo...
482  https://www.waitrose.com/ecom/products/waitros...
483  https://www.waitrose.com/ecom/products/dr-oetk...
484  https://www.waitrose.com/ecom/products/cohens-...

                                                  name product-size   price  \
0                           Mr Kipling Viennese Whirls           6s   £1.98
1                            Mr Kipling French Fancies           8s   £2.36
2                            Mr Kipling 8 Angel Slices           8s   £2.96
3                       Waitrose 4 Brioche Burger Buns           4s   £1.31
4       Hovis Seed Sensations Multiseeded Sliced Bread         800g   £1.90
..                                                 ...          ...     ...
480                         Galaxy Chocolate Cake Bars           5s   £2.25
481                                 25cm Football Cake         each  £30.00
482  Waitrose Ready To Bake 4 All Butter Cinnamon S...         360g   £2.60
483             Dr. Oetker Old School Cake Mix Vanilla         436g   £3.00
484                 Cohens Bakery Buckingham Rye Bread         400g   £2.10

    price-per-unit                 offer-description category
0         33p each                25% Off. Was £2.65   Bakery
1       29.5p each                25% Off. Was £3.15   Bakery
2         37p each                25% Off. Was £3.95   Bakery
3       32.8p each                25% Off. Was £1.75   Bakery
4       23.8p/100g                               NaN   Bakery
..             ...                               ...      ...
480       45p each                               NaN   Bakery
481       £30 each                               NaN   Bakery
482       £7.23/kg  Introductory Offer.Will be £3.30   Bakery
483       £6.89/kg                               NaN   Bakery
484     52.5p/100g                               NaN   Bakery

[485 rows x 12 columns]>

In [34]:
df.columns

Index(['id', 'data-product-type', 'data-product-on-offer',
       'data-product-index', 'image-url', 'product-page', 'name',
       'product-size', 'price', 'price-per-unit', 'offer-description',
       'category'],
      dtype='object')

What are the ids that appear more than once in the data frame? Print out the values of these ids.

In [35]:
duplicated_values = df["id"].duplicated()
print(df[duplicated_values]['id'])

160     56312
245    872615
276    684311
Name: id, dtype: int64

In [36]:
duplicated_values = df["id"].duplicated()
print(df[duplicated_values]["id"].values)

[ 56312 872615 684311]

In [37]:
df = df.drop_duplicates()

Remove all the £ symbols from the price column.

In [38]:
df.loc[df["price"].str.contains("p"), "price"] = df["price"].apply(lambda x: "0."+ str.replace(x,"p",''))

In [39]:
df.loc[df["price"].str.contains("£"), "price"]= df["price"].str.replace("£","")

In [40]:
df['price'] = df['price'].astype('float')

C:\Users\Oviya S\AppData\Local\Temp\ipykernel_18352\1977906226.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['price'] = df['price'].astype('float')

In [41]:
df

,id,data-product-type,data-product-on-offer,data-product-index,image-url,product-page,name,product-size,price,price-per-unit,offer-description,category
0,872615,G,True,246,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/mr-kipl...,Mr Kipling Viennese Whirls,6s,1.98,33p each,25% Off. Was £2.65,Bakery
1,56312,G,True,161,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/mr-kipl...,Mr Kipling French Fancies,8s,2.36,29.5p each,25% Off. Was £3.15,Bakery
2,684311,G,True,277,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/mr-kipl...,Mr Kipling 8 Angel Slices,8s,2.96,37p each,25% Off. Was £3.95,Bakery
3,540706,G,True,4,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/waitros...,Waitrose 4 Brioche Burger Buns,4s,1.31,32.8p each,25% Off. Was £1.75,Bakery
4,783454,G,False,5,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/hovis-s...,Hovis Seed Sensations Multiseeded Sliced Bread,800g,1.90,23.8p/100g,NaN,Bakery
...,...,...,...,...,...,...,...,...,...,...,...,...
480,384230,G,False,481,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/galaxy-...,Galaxy Chocolate Cake Bars,5s,2.25,45p each,NaN,Bakery
481,376437,E,False,482,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/25cm-fo...,25cm Football Cake,each,30.00,£30 each,NaN,Bakery
482,374515,G,True,483,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/waitros...,Waitrose Ready To Bake 4 All Butter Cinnamon S...,360g,2.60,£7.23/kg,Introductory Offer.Will be £3.30,Bakery
483,297903,G,False,484,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/dr-oetk...,Dr. Oetker Old School Cake Mix Vanilla,436g,3.00,£6.89/kg,NaN,Bakery
484,77133,G,False,485,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/cohens-...,Cohens Bakery Buckingham Rye Bread,400g,2.10,52.5p/100g,NaN,Bakery

Remove all the £ symbols from the price column.

In [47]:
item_price_list = df['price'].tolist()
new_list = []
for element in item_price_list:
    element_str = str(element)
    if '£' in element_str:
        new_element = element_str.replace("£", "")
    elif "p" in element_str:
        new_element = element_str.replace("p", "")
        new_element = "0." + new_element
    else:
        new_element = element_str
    new_list.append(new_element)
df["item_price_fixed"] = new_list
df["item_price_fixed"] = df["item_price_fixed"].astype(float)

C:\Users\Oviya S\AppData\Local\Temp\ipykernel_18352\2541204019.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["item_price_fixed"] = new_list
C:\Users\Oviya S\AppData\Local\Temp\ipykernel_18352\2541204019.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["item_price_fixed"] = df["item_price_fixed"].astype(float)

In [48]:
new_list

['1.98',
 '2.36',
 '2.96',
 '1.31',
 '1.9',
 '1.3',
 '1.0',
 '2.0',
 '1.1',
 '2.5',
 '1.85',
 '1.0',
 '1.85',
 '2.2',
 '1.5',
 '0.65',
 '0.9',
 '1.45',
 '1.1',
 '0.65',
 '2.0',
 '1.95',
 '1.55',
 '1.2',
 '0.7',
 '1.25',
 '2.5',
 '1.2',
 '1.9',
 '1.35',
 '0.9',
 '1.45',
 '1.28',
 '1.6',
 '1.45',
 '0.8',
 '1.68',
 '1.0',
 '0.9',
 '2.4',
 '1.3',
 '2.1',
 '2.2',
 '1.25',
 '2.5',
 '1.68',
 '2.0',
 '2.15',
 '1.7',
 '0.5',
 '0.9',
 '1.35',
 '1.85',
 '0.75',
 '1.25',
 '1.4',
 '1.9',
 '1.0',
 '2.0',
 '2.7',
 '1.95',
 '1.5',
 '1.45',
 '2.2',
 '1.45',
 '2.3',
 '0.7',
 '1.55',
 '2.0',
 '2.3',
 '2.0',
 '1.95',
 '1.6',
 '1.25',
 '1.65',
 '1.75',
 '2.0',
 '1.28',
 '2.75',
 '0.75',
 '1.5',
 '2.35',
 '1.8',
 '1.45',
 '1.1',
 '2.4',
 '1.5',
 '2.15',
 '2.5',
 '0.9',
 '2.0',
 '2.96',
 '3.0',
 '2.2',
 '1.55',
 '1.75',
 '1.25',
 '1.5',
 '2.96',
 '1.85',
 '1.3',
 '2.0',
 '1.75',
 '3.5',
 '1.9',
 '3.5',
 '1.7',
 '3.1',
 '3.5',
 '2.4',
 '1.4',
 '2.4',
 '1.6',
 '1.5',
 '2.2',
 '1.6',
 '1.6',
 '1.35',
 '2.7',
 '2.0',
 '2.1',
 '1.9',
 '2.3',
 '1.5',
 '1.35',
 '2.0',
 '1.3',
 '0.8',
 '4.0',
 '0.7',
 '1.44',
 '1.6',
 '1.35',
 '1.2',
 '2.96',
 '2.5',
 '2.0',
 '2.0',
 '2.1',
 '1.56',
 '1.52',
 '1.45',
 '2.0',
 '2.6',
 '2.0',
 '1.52',
 '2.96',
 '2.0',
 '1.95',
 '0.6',
 '2.5',
 '1.1',
 '1.3',
 '2.6',
 '6.5',
 '2.75',
 '1.4',
 '2.1',
 '1.8',
 '2.0',
 '2.55',
 '1.8',
 '3.0',
 '1.25',
 '3.0',
 '2.4',
 '1.6',
 '2.55',
 '17.0',
 '1.5',
 '1.35',
 '1.35',
 '2.8',
 '2.96',
 '2.3',
 '1.6',
 '3.5',
 '0.75',
 '2.1',
 '3.5',
 '2.3',
 '2.1',
 '1.35',
 '2.55',
 '0.7',
 '2.35',
 '2.17',
 '2.95',
 '4.7',
 '3.1',
 '3.95',
 '1.3',
 '1.65',
 '2.0',
 '2.2',
 '3.4',
 '2.8',
 '2.2',
 '3.5',
 '1.9',
 '2.3',
 '2.3',
 '2.8',
 '2.2',
 '1.3',
 '2.6',
 '2.96',
 '2.6',
 '2.0',
 '2.4',
 '2.1',
 '2.0',
 '6.5',
 '2.75',
 '2.3',
 '1.95',
 '1.15',
 '3.0',
 '1.5',
 '1.1',
 '2.0',
 '2.3',
 '1.9',
 '1.5',
 '3.15',
 '1.85',
 '1.5',
 '1.25',
 '1.75',
 '2.0',
 '6.5',
 '2.25',
 '3.65',
 '1.1',
 '2.2',
 '1.15',
 '1.65',
 '3.0',
 '2.6',
 '1.7',
 '0.6',
 '2.0',
 '1.5',
 '4.0',
 '2.2',
 '2.9',
 '1.5',
 '2.1',
 '1.75',
 '3.0',
 '1.95',
 '2.0',
 '1.7',
 '2.2',
 '4.9',
 '3.0',
 '1.5',
 '3.15',
 '2.15',
 '1.8',
 '2.3',
 '2.5',
 '2.55',
 '1.75',
 '2.25',
 '3.1',
 '1.9',
 '1.5',
 '1.3',
 '3.15',
 '3.25',
 '2.0',
 '1.4',
 '2.5',
 '2.5',
 '3.15',
 '12.5',
 '3.0',
 '1.1',
 '1.9',
 '2.5',
 '2.0',
 '0.6',
 '1.95',
 '3.0',
 '1.8',
 '4.6',
 '2.6',
 '2.65',
 '2.5',
 '3.15',
 '1.1',
 '4.0',
 '3.5',
 '2.0',
 '2.0',
 '3.0',
 '3.0',
 '6.5',
 '4.6',
 '2.0',
 '2.95',
 '2.9',
 '2.95',
 '2.9',
 '3.25',
 '2.5',
 '1.3',
 '12.5',
 '2.9',
 '1.5',
 '15.0',
 '16.5',
 '3.25',
 '2.9',
 '2.4',
 '2.65',
 '1.9',
 '8.5',
 '1.3',
 '2.5',
 '2.15',
 '1.35',
 '2.5',
 '1.5',
 '1.0',
 '0.9',
 '1.85',
 '2.5',
 '3.15',
 '2.0',
 '3.0',
 '6.5',
 '1.0',
 '1.3',
 '3.25',
 '7.0',
 '1.55',
 '1.6',
 '4.15',
 '2.0',
 '2.0',
 '3.15',
 '2.5',
 '4.15',
 '3.0',
 '3.95',
 '1.3',
 '5.1',
 '14.0',
 '7.0',
 '3.25',
 '2.5',
 '2.25',
 '1.9',
 '1.5',
 '1.88',
 '32.0',
 '26.0',
 '1.2',
 '2.2',
 '2.0',
 '2.25',
 '1.75',
 '2.5',
 '23.0',
 '2.6',
 '3.0',
 '2.0',
 '7.0',
 '15.0',
 '3.95',
 '12.0',
 '2.65',
 '28.0',
 '1.7',
 '1.35',
 '2.0',
 '4.0',
 '3.15',
 '26.0',
 '10.0',
 '1.2',
 '1.7',
 '23.0',
 '1.75',
 '15.0',
 '2.1',
 '3.75',
 '2.6',
 '2.2',
 '3.95',
 '7.0',
 '3.45',
 '2.5',
 '16.0',
 '45.0',
 '10.0',
 '1.5',
 '2.2',
 '2.75',
 '1.95',
 '3.6',
 '2.5',
 '40.0',
 '35.0',
 '4.0',
 '3.15',
 '26.0',
 '4.7',
 '4.0',
 '8.5',
 '1.1',
 '5.3',
 '40.0',
 '40.0',
 '3.8',
 '1.2',
 '35.0',
 '30.0',
 '16.0',
 '16.0',
 '1.87',
 '26.0',
 '1.75',
 '26.0',
 '35.0',
 '2.95',
 '16.0',
 '16.5',
 '28.0',
 '40.0',
 '4.15',
 '35.0',
 '3.5',
 '35.0',
 '4.0',
 '16.0',
 '1.7',
 '15.0',
 '14.0',
 '2.65',
 '26.0',
 '14.0',
 '1.1',
 '35.0',
 '35.0',
 '10.0',
 '16.0',
 '28.0',
 '16.0',
 '2.3',
 '2.5',
 '4.0',
 '7.0',
 '16.5',
 '15.0',
 '16.0',
 '2.35',
 '2.1',
 '8.0',
 '14.0',
 '15.0',
 '2.1',
 '35.0',
 '40.0',
 '1.5',
 '32.0',
 '2.6',
 '2.1',
 '1.75',
 '7.0',
 '5.5',
 '2.1',
 '1.75',
 '3.0',
 '10.0',
 '2.25',
 '30.0',
 '2.6',
 '3.0',
 '2.1']

In [50]:
df["id"] = df["id"].astype("int32")

C:\Users\Oviya S\AppData\Local\Temp\ipykernel_18352\2999544582.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["id"] = df["id"].astype("int32")

In [52]:
df.info

<bound method DataFrame.info of          id data-product-type  data-product-on-offer  data-product-index  \
0    872615                 G                   True                 246
1     56312                 G                   True                 161
2    684311                 G                   True                 277
3    540706                 G                   True                   4
4    783454                 G                  False                   5
..      ...               ...                    ...                 ...
480  384230                 G                  False                 481
481  376437                 E                  False                 482
482  374515                 G                   True                 483
483  297903                 G                  False                 484
484   77133                 G                  False                 485

                                             image-url  \
0    https://ecom-su-static-prod.wtrecom.com/images...
1    https://ecom-su-static-prod.wtrecom.com/images...
2    https://ecom-su-static-prod.wtrecom.com/images...
3    https://ecom-su-static-prod.wtrecom.com/images...
4    https://ecom-su-static-prod.wtrecom.com/images...
..                                                 ...
480  https://ecom-su-static-prod.wtrecom.com/images...
481  https://ecom-su-static-prod.wtrecom.com/images...
482  https://ecom-su-static-prod.wtrecom.com/images...
483  https://ecom-su-static-prod.wtrecom.com/images...
484  https://ecom-su-static-prod.wtrecom.com/images...

                                          product-page  \
0    https://www.waitrose.com/ecom/products/mr-kipl...
1    https://www.waitrose.com/ecom/products/mr-kipl...
2    https://www.waitrose.com/ecom/products/mr-kipl...
3    https://www.waitrose.com/ecom/products/waitros...
4    https://www.waitrose.com/ecom/products/hovis-s...
..                                                 ...
480  https://www.waitrose.com/ecom/products/galaxy-...
481  https://www.waitrose.com/ecom/products/25cm-fo...
482  https://www.waitrose.com/ecom/products/waitros...
483  https://www.waitrose.com/ecom/products/dr-oetk...
484  https://www.waitrose.com/ecom/products/cohens-...

                                                  name product-size  price  \
0                           Mr Kipling Viennese Whirls           6s   1.98
1                            Mr Kipling French Fancies           8s   2.36
2                            Mr Kipling 8 Angel Slices           8s   2.96
3                       Waitrose 4 Brioche Burger Buns           4s   1.31
4       Hovis Seed Sensations Multiseeded Sliced Bread         800g   1.90
..                                                 ...          ...    ...
480                         Galaxy Chocolate Cake Bars           5s   2.25
481                                 25cm Football Cake         each  30.00
482  Waitrose Ready To Bake 4 All Butter Cinnamon S...         360g   2.60
483             Dr. Oetker Old School Cake Mix Vanilla         436g   3.00
484                 Cohens Bakery Buckingham Rye Bread         400g   2.10

    price-per-unit                 offer-description category  \
0         33p each                25% Off. Was £2.65   Bakery
1       29.5p each                25% Off. Was £3.15   Bakery
2         37p each                25% Off. Was £3.95   Bakery
3       32.8p each                25% Off. Was £1.75   Bakery
4       23.8p/100g                               NaN   Bakery
..             ...                               ...      ...
480       45p each                               NaN   Bakery
481       £30 each                               NaN   Bakery
482       £7.23/kg  Introductory Offer.Will be £3.30   Bakery
483       £6.89/kg                               NaN   Bakery
484     52.5p/100g                               NaN   Bakery

     item_price_fixed
0                1.98
1                2.36
2                2.96
3                1.31
4                1.90
..                ...
480              2.25
481             30.00
482              2.60
483              3.00
484              2.10

[482 rows x 13 columns]>